name: ci

on: [push]

jobs:
  tests:
    name: Forge Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - uses: huff-language/huff-toolchain@v2
        with:
          version: nightly
      - name: dependencies
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.4.24/solc-static-linux
          cp ./solc-static-linux ~/.cargo/bin/solc
          chmod 744 ~/.cargo/bin/solc
      - name: tests
        run: |
          forge --version
          forge install
          forge test --ffi -vvvvv